//
// Created by theo on 10/24/2021.
//

#ifndef UMDWITHCLASS3_CONFIG_JSON_KEYWORDS_H
#define UMDWITHCLASS3_CONFIG_JSON_KEYWORDS_H

#define CONFIG_JSON_FILE_NAME "/sysInfo.json"

#define CONFIG_JSON_SCREEN_ADDRESS "screenAddress"
#define CONFIG_JSON_HAS_SCREEN "hasScreen"
#define CONFIG_JSON_DEFAULT_COM "defCom"
#define CONFIG_JSON_COM_NAME "comName"
#define CONFIG_JSON_SERIAL_NUMBER "SN"
#define CONFIG_JSON_BATTERY_OBJECT "battery"
#define CONFIG_JSON_BATTERY_NAME "name"
#define CONFIG_JSON_BATTERY_CAPACITY "capacity"

#endif //UMDWITHCLASS3_CONFIG_JSON_KEYWORDS_H
